spring.application.name=demo
server.port=6969

#db config
spring.datasource.url=jdbc:mysql://localhost:3306/mbav2
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=PUT_A_LONG_RANDOM_SECRET_HERE_AT_LEAST_32_CHARS
jwt.expiration-ms=86400000