spring.application.name=demo
server.port=6969

#db config
spring.datasource.url=jdbc:mysql://localhost:3306/mbav2
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=S8QzJ5aXwK0vP2rYhN7bE4Lm9cDfWx1Ua6RgZi3NePt=
jwt.expiration-ms=86400000